"""
Execution plan and Tool information schemas.
"""
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from satquery.schemas.models import ModelProvenance


class ToolInfo(BaseModel):
    """Metadata describing a specialist remote sensing tool."""
    name: str = Field(..., description="Tool name identifier")
    version: str = Field("v3", description="Tool version")
    tasks: List[str] = Field(..., description="Supported tasks for this tool")
    modalities: List[str] = Field(default_factory=lambda: ["OPTICAL"], description="Supported sensor modalities")
    provenance: ModelProvenance = Field(ModelProvenance.HEURISTIC, description="Tool execution provenance")
    status: str = Field("READY", description="Tool readiness status")
    description: str = Field("", description="Human-readable tool description")


class ExecutionPlan(BaseModel):
    """Declarative execution workflow plan generated by ExecutionPlanner."""
    plan_id: str = Field(..., description="Unique plan identifier (e.g., 'PLAN_A_VQA')")
    name: str = Field(..., description="Human-readable workflow title")
    stages: List[str] = Field(..., description="Ordered list of execution pipeline stages")
    primary_tool: str = Field(..., description="Primary tool executing core analytical reasoning")
    auxiliary_tools: List[str] = Field(default_factory=list, description="Supplementary specialist tools")
    requires_dual_input: bool = Field(False, description="True if workflow requires two satellite images")
    description: str = Field("", description="Workflow rationale")
